version: "3"

services:
  frontend:
    #Dockerfile의 경로
    build: ./MATHRONE_Frontend_Submodule
    command: ["npm", "start"]
    ports:
      - 3000:3000
    networks:
      - app-tier
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리(작업공간 app으로 설정해줌 -> frontend/Dockerfile)
    volumes:
      - ./MATHRONE_Frontend_Submodule:/app
  backend:
    build: ./MATHRONE_Backend_Submodule
    ports:
      - 8080:8080
    networks:
      - app-tier
    volumes:
      - ./src/main/resources/application-kakao.properties:/tmp/application-kakao.properties
    environment:
      - spring.config.additional-location=file:///tmp/application-kakao.properties
  redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis
      hostname: redis
      networks:
        - app-tier
      ports:
        - 6379:6379
      volumes:
      - ./redis:/data
networks:
  app-tier:
    driver: bridge
