name: Deploy to Amazon EC2

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  PROJECT_NAME: ${{secrets.PROJECT_NAME}}
  BUCKET_NAME: ${{secrets.BUCKET_NAME}}
  CODE_DEPLOY_APP_NAME: ${{secrets.PROJECT_NAME}}
  DEPLOYMENT_GROUP_NAME: ${{secrets.BUCKET_NAME}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
      
    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" > .env
        cd /home/runner/work/MATHRONE_Docker/MATHRONE_Docker/MATHRONE_Backend_Submodule/src/main/resources
        echo "${{ secrets.BACK_PROPS }}" > application.properties
        cd /home/runner/work/MATHRONE_Docker/MATHRONE_Docker/MATHRONE_Backend_Submodule/src/main/resources/keys
        echo "${{ secrets.JWT_PROPS }}" > jwtKey.properties

    - name: Grant execute permission for gradlew
      run: |
        cd ./MATHRONE_Backend_Submodule
        chmod +x gradlew

    - name: Build with Gradle
      run: |
        cd ./MATHRONE_Backend_Submodule
        ./gradlew build

    - name: Make Zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Delete all files on S3
      run: aws s3 rm s3://$BUCKET_NAME/ --recursive --include "*"

    - name: Upload zip files on S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
      
    - name: Code deploy
      run: >
        aws deploy create-deployment
        --application-name $CODE_DEPLOY_APP_NAME
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name $DEPLOYMENT_GROUP_NAME
        --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
